import {Component,lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import projectData from './generated/projects.json';
import type {Project,Quality} from './types';
import {chapters,chapterAt,clamp} from './scene/timeline.mjs';
const Scene=lazy(()=>import('./scene/Scene'));
const projects=projectData as Project[];
class SceneBoundary extends Component<{children:ReactNode;onError:()=>void},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true}}componentDidCatch(){this.props.onError()}render(){return this.state.error?null:this.props.children}}
type Panel={type:'projects'|'contact'|'display'}|{type:'project';id:string}|null;
export default function App(){
 const reducedQuery=useRef(window.matchMedia('(prefers-reduced-motion: reduce)'));
 const [reduced,setReduced]=useState(reducedQuery.current.matches);
 const [reading,setReading]=useState(reducedQuery.current.matches);
 const [quality,setQuality]=useState<Quality>(()=>(localStorage.getItem('tree-quality') as Quality)||'auto');
 const [chapterId,setChapterId]=useState('opening');const [panel,setPanel]=useState<Panel>(null);const [ready,setReady]=useState(false);const [failed,setFailed]=useState(false);const [retry,setRetry]=useState(0);
 const progress=useRef(0);const anchorRef=useRef<HTMLDivElement>(null);const dialog=useRef<HTMLDialogElement>(null);const lastFocus=useRef<HTMLElement|null>(null);const previousHash=useRef('');
 const current=chapters.find(c=>c.id===chapterId)??chapters[0];const project=projects.find(p=>p.id===current.project);const selected=panel?.type==='project'?projects.find(p=>p.id===panel.id):undefined;
 const displayReading=reading||failed;
 useEffect(()=>{const fn=(e:MediaQueryListEvent)=>{setReduced(e.matches);if(e.matches)setReading(true)};reducedQuery.current.addEventListener('change',fn);return()=>reducedQuery.current.removeEventListener('change',fn)},[]);
 useEffect(()=>{const scroll=()=>{if(panel||displayReading)return;progress.current=clamp(window.scrollY/Math.max(1,document.documentElement.scrollHeight-window.innerHeight));if(!ready)setChapterId(chapterAt(progress.current).id)};window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);scroll();return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll)}},[panel,ready,displayReading]);
 const goChapter=useCallback((id:string,writeHash=true)=>{const c=chapters.find(c=>c.id===id);if(!c)return;setReading(false);setPanel(null);const p=c.id==='opening'?0:c.id==='ending'?1:c.start+(c.end-c.start)*.4;progress.current=p;setChapterId(c.id);requestAnimationFrame(()=>{window.scrollTo({top:p*(document.documentElement.scrollHeight-innerHeight),behavior:'instant' as ScrollBehavior});if(writeHash)history.pushState({chapter:id},'',`#chapter/${id}`)})},[]);
 useEffect(()=>{function route(){const [kind,id]=location.hash.slice(1).split('/');if(kind==='project'&&projects.some(p=>p.id===id)){setPanel({type:'project',id});}else if(kind==='chapter'){goChapter(id,false)}else if(kind==='projects'||kind==='contact'||kind==='display'){setPanel({type:kind})}else{setPanel(null);if(kind==='reading')setReading(true);}}
 window.addEventListener('hashchange',route);window.addEventListener('popstate',route);route();return()=>{window.removeEventListener('hashchange',route);window.removeEventListener('popstate',route)}},[goChapter]);
 useEffect(()=>{const d=dialog.current;if(panel&&d){if(!d.open)d.showModal();document.body.classList.add('dialog-open');d.scrollTop=0;}else if(d?.open){d.close();document.body.classList.remove('dialog-open');lastFocus.current?.focus({preventScroll:true});}return()=>document.body.classList.remove('dialog-open')},[panel]);
 const open=(next:Exclude<Panel,null>)=>{if(!panel){lastFocus.current=document.activeElement as HTMLElement;previousHash.current=location.hash;}setPanel(next);const hash=next.type==='project'?`project/${next.id}`:next.type;history.pushState({panel:true},'',`#${hash}`)};
 const close=()=>{setPanel(null);history.replaceState(null,'',previousHash.current||location.pathname);};
 const enterReading=()=>{setReading(true);setPanel(null);history.pushState(null,'','#reading');window.scrollTo(0,0)};
 const sceneReady=useCallback(()=>setReady(true),[]);const sceneError=useCallback(()=>{setFailed(true);setReady(false)},[]);const pick=useCallback((branch:string)=>{const c=chapters.find(c=>c.id===branch);if(c?.project){lastFocus.current=document.activeElement as HTMLElement;previousHash.current=location.hash;setPanel({type:'project',id:c.project});history.pushState({panel:true},'',`#project/${c.project}`)}},[]);
 useEffect(()=>{if(ready||failed||displayReading)return;const timer=setTimeout(()=>setFailed(true),12000);return()=>clearTimeout(timer)},[ready,failed,displayReading,retry]);
 return <>
  <a className="skip-link" href="/reading.html">Skip to the written portfolio</a>
  <header className="site-header"><a className="identity" href="#chapter/opening" onClick={e=>{e.preventDefault();goChapter('opening')}} aria-label="Cride, return to beginning"><span className="identity-name">cride<span className="identity-period">.</span></span><span className="identity-role">SOFTWARE ENGINEER</span></a><div className="utilities"><button onClick={()=>open({type:'projects'})}>Projects <span className="count">08</span></button><button className="reading-toggle" onClick={displayReading?()=>goChapter('opening'):enterReading}>{displayReading?'Explore the tree':'Reading mode'}</button><button onClick={()=>open({type:'contact'})}>Contact <span aria-hidden="true">↗</span></button></div></header>
  {!displayReading?<>
   <div className="scene-stage" aria-hidden="true"><img className={`opening-image ${ready?'is-ready':''}`} src="/assets/opening.webp" alt=""/><SceneBoundary key={retry} onError={sceneError}><Suspense fallback={null}><Scene progress={progress} paused={!!panel} reduced={reduced} quality={quality} onReady={sceneReady} onError={sceneError} onChapter={setChapterId} onPick={pick} anchorRef={anchorRef}/></Suspense></SceneBoundary></div>
   <div className="scene-vignette" aria-hidden="true"/>
   <main className="journey" aria-label="Cinematic engineering history"><section className={`annotation ${chapterId==='transition'?'transition-note':''}`} key={chapterId} aria-labelledby="chapter-title">
    <div className="eyebrow"><span className="fine-rule"/>{chapterId==='opening'?'A CONTINUOUS WORK IN PROGRESS':chapterId==='ending'?'THE STORY SO FAR':`${current.index} / ${current.label.toUpperCase()}`}</div>
    <h1 id="chapter-title">{project?project.title:chapterId==='opening'?<>Nothing grows<br/> in isolation.</>:chapterId==='ending'?<>Still learning.<br/> Still growing.</>:<>From systems<br/> to intelligence.</>}</h1>
    <p className="annotation-description">{project?project.shortDescription:chapterId==='opening'?'A living record of the things I’ve built, the problems I’ve followed, and the ideas that grew from them.':chapterId==='ending'?'Every branch begins somewhere. The next one is still taking shape.':'The same curiosity. A new kind of architecture.'}</p>
    {project&&<><p className="project-name">{project.projectName}</p><div className="annotation-facts">{project.id==='papai-rag'?<><span>4,500+ catalogs</span><span>~1.6M records</span><span>Entirely local</span></>:project.id==='foundations'?<><span>98% technician exam</span><span>C / C++ / C#</span></>:project.technologies.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><button className="text-action" onClick={()=>open({type:'project',id:project.id})}>Explore project <span aria-hidden="true">↗</span></button></>}
    {chapterId==='opening'&&<button className="begin-link" onClick={()=>goChapter('foundations')}><span className="scroll-stroke" aria-hidden="true"/>Scroll to explore</button>}
    {chapterId==='ending'&&<button className="text-action" onClick={()=>open({type:'contact'})}>Let’s connect <span aria-hidden="true">↗</span></button>}
   </section></main>
   <div className="world-anchor" ref={anchorRef} aria-hidden="true"><span/>{project?.projectName}</div>
   <div className="scroll-track" aria-hidden="true"/>
   <footer className="journey-footer"><div className="chapter-caption"><span>{current.index}</span><span className="caption-rule"/><span>{current.label}</span></div><nav className="chapter-dots" aria-label="Explore chapters">{chapters.filter(c=>c.id!=='transition').map(c=><button key={c.id} onClick={()=>goChapter(c.id)} aria-label={`Go to ${c.label}`} aria-current={chapterId===c.id?'step':undefined}><span/><span className="chapter-tooltip">{c.label}</span></button>)}</nav><button className="display-button" onClick={()=>open({type:'display'})} aria-label="Display options"><span className="display-symbol" aria-hidden="true">◐</span><span>{!ready?'Preparing the tree':quality==='auto'?'Adaptive quality':`${quality} quality`}</span></button></footer>
  </>:<main className="reading-page"><div className="eyebrow">CRIDE / AN ENGINEERING HISTORY</div><h1>It starts with curiosity.</h1><p className="reading-intro">From native systems to local AI. The projects, problems, and ideas behind the tree.</p>{failed&&<p className="fallback-message">The 3D scene is unavailable on this visit. Every project is available below. <button onClick={()=>{setFailed(false);setReady(false);setRetry(x=>x+1);setReading(false)}}>Try the tree again</button></p>}<img className="reading-tree" src="/assets/opening.webp" alt="An original pale, leafless tree with roots and asymmetrical branches, representing the connected development of engineering skills."/><nav className="reading-index" aria-label="Written projects">{projects.map((p,i)=><a key={p.id} href={`#read-${p.id}`}><span>{String(i+1).padStart(2,'0')}</span>{p.projectName}<span aria-hidden="true">↓</span></a>)}</nav>{projects.map(p=><article className="reading-project" id={`read-${p.id}`} key={p.id}><div className="eyebrow">{p.category}</div><h2>{p.projectName}</h2><div dangerouslySetInnerHTML={{__html:p.html}}/><p className="technology-line">{p.technologies.join(' · ')}</p></article>)}<button className="text-action" onClick={()=>open({type:'contact'})}>Connect with Cride ↗</button></main>}
  <dialog className={`reading-dialog ${panel?.type==='project'?'project-dialog':''}`} ref={dialog} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}}} aria-labelledby="dialog-title"><div className="dialog-top"><span className="eyebrow">{selected?'PROJECT NOTES':'CRIDE / ENGINEERING HISTORY'}</span><button className="close-button" onClick={close} aria-label="Close panel">Close <span aria-hidden="true">×</span></button></div>
   {panel?.type==='projects'&&<><h2 id="dialog-title">The branches.</h2><p>Different problems. Connected foundations.</p><div className="project-index">{projects.map((p,i)=><button key={p.id} onClick={()=>open({type:'project',id:p.id})}><span className="index-number">{String(i+1).padStart(2,'0')}</span><span><strong>{p.projectName}</strong><small>{p.category}</small></span><span aria-hidden="true">↗</span></button>)}</div><a className="text-action" href="/reading.html">Open the complete written portfolio ↗</a></>}
   {selected&&<><div className="eyebrow project-category">{selected.category}</div><h2 id="dialog-title">{selected.projectName}</h2><p className="project-lede">{selected.shortDescription}</p><div className="project-prose" dangerouslySetInnerHTML={{__html:selected.html}}/><div className="detail-technologies"><h3>Technologies & disciplines</h3><p>{selected.technologies.join(' · ')}</p></div><div className="related-projects"><h3>Connected work</h3>{selected.relatedProjects.map(id=>{const p=projects.find(x=>x.id===id)!;return <button key={id} onClick={()=>open({type:'project',id})}>{p.projectName}<span aria-hidden="true">↗</span></button>})}</div><button className="text-action" onClick={()=>{close();goChapter(chapters.find(c=>c.project===selected.id||c.id===selected.branchId)?.id??'reverse-engineering')}}>Find this branch in the tree →</button></>}
   {panel?.type==='contact'&&<><h2 id="dialog-title">The next conversation.</h2><p className="project-lede">Software engineering, systems, and the ideas between them.</p><a className="contact-link" href="https://github.com/cride9" target="_blank" rel="noreferrer"><span>GitHub<small>@cride9</small></span><span aria-hidden="true">↗</span></a><p className="contact-note">Explore my public work and profile on GitHub.</p></>}
   {panel?.type==='display'&&<><h2 id="dialog-title">A quieter view.</h2><fieldset><legend>Rendering quality</legend>{(['auto','high','low'] as Quality[]).map(q=><label className="quality-option" key={q}><span><strong>{q==='auto'?'Adaptive':q==='high'?'High fidelity':'Lightweight'}</strong><small>{q==='auto'?'Adjust to your device.':q==='high'?'More detail and softer shadows.':'Less detail, lower graphics workload.'}</small></span><input type="radio" name="quality" value={q} checked={quality===q} onChange={()=>{setQuality(q);localStorage.setItem('tree-quality',q)}}/></label>)}</fieldset><div className="display-reading"><h3>Prefer to read?</h3><p>Explore every project without camera movement.</p><button className="text-action" onClick={()=>{close();enterReading()}}>Switch to reading mode →</button></div></>}
  </dialog>
 </>;
}
